# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clova_speech.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'clova_speech.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63lova_speech.proto\x12\x0b\x63lovaspeech\"\x81\x01\n\x10RecognizeRequest\x12.\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x1c.clovaspeech.RecognizeConfigH\x00\x12\x32\n\raudio_content\x18\x02 \x01(\x0b\x32\x19.clovaspeech.AudioContentH\x00\x42\t\n\x07request\"\xa8\x01\n\x0fRecognizeConfig\x12\x15\n\rlanguage_code\x18\x01 \x01(\t\x12,\n\x08\x65ncoding\x18\x02 \x01(\x0e\x32\x1a.clovaspeech.AudioEncoding\x12\x19\n\x11sample_rate_hertz\x18\x03 \x01(\x05\x12\x0e\n\x06\x64omain\x18\x04 \x01(\t\x12\r\n\x05model\x18\x05 \x01(\t\x12\x16\n\x0e\x65nable_partial\x18\x06 \x01(\x08\"\x1f\n\x0c\x41udioContent\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"\xb5\x01\n\x11RecognizeResponse\x12,\n\x0bresult_type\x18\x01 \x01(\x0e\x32\x17.clovaspeech.ResultType\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12$\n\x05words\x18\x04 \x03(\x0b\x32\x15.clovaspeech.WordInfo\x12\x15\n\rstart_time_ms\x18\x05 \x01(\x03\x12\x13\n\x0b\x65nd_time_ms\x18\x06 \x01(\x03\"N\n\x08WordInfo\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x10\n\x08start_ms\x18\x02 \x01(\x03\x12\x0e\n\x06\x65nd_ms\x18\x03 \x01(\x03\x12\x12\n\nconfidence\x18\x04 \x01(\x02*2\n\rAudioEncoding\x12\x0c\n\x08LINEAR16\x10\x00\x12\x08\n\x04\x46LAC\x10\x01\x12\t\n\x05MULAW\x10\x02*$\n\nResultType\x12\x0b\n\x07PARTIAL\x10\x00\x12\t\n\x05\x46INAL\x10\x01\x32\x64\n\x12\x43lovaSpeechService\x12N\n\tRecognize\x12\x1d.clovaspeech.RecognizeRequest\x1a\x1e.clovaspeech.RecognizeResponse(\x01\x30\x01\x42*\n\x16\x63om.ncloud.clovaspeechB\x10\x43lovaSpeechProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clova_speech_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ncloud.clovaspeechB\020ClovaSpeechProto'
  _globals['_AUDIOENCODING']._serialized_start=635
  _globals['_AUDIOENCODING']._serialized_end=685
  _globals['_RESULTTYPE']._serialized_start=687
  _globals['_RESULTTYPE']._serialized_end=723
  _globals['_RECOGNIZEREQUEST']._serialized_start=36
  _globals['_RECOGNIZEREQUEST']._serialized_end=165
  _globals['_RECOGNIZECONFIG']._serialized_start=168
  _globals['_RECOGNIZECONFIG']._serialized_end=336
  _globals['_AUDIOCONTENT']._serialized_start=338
  _globals['_AUDIOCONTENT']._serialized_end=369
  _globals['_RECOGNIZERESPONSE']._serialized_start=372
  _globals['_RECOGNIZERESPONSE']._serialized_end=553
  _globals['_WORDINFO']._serialized_start=555
  _globals['_WORDINFO']._serialized_end=633
  _globals['_CLOVASPEECHSERVICE']._serialized_start=725
  _globals['_CLOVASPEECHSERVICE']._serialized_end=825
# @@protoc_insertion_point(module_scope)
